version: '3.9'

services:
  web:
    build: .
    ports:
      - '3000:3000'

  database:
    image: mongo:5.0-alpine

# To start the Docker services
# docker-compose up -d

# To stop the Docker services
# docker-compose down